---
# tasks file for zabbix-repo

- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-default.yml"
  tags:
    - zabbix-repo 

# Debian  specific tasks
- include: repo-common.yml
  when: zabbix_repo_enabled
  tags:
    - zabbix-repo 

# Debian  specific tasks
- include: repo-Debian.yml
  when: ansible_distribution in ('Debian', 'Ubuntu') and zabbix_repo_enabled
  tags:
    - zabbix-repo 

# CentOS  specific tasks
- include: repo-CentOS.yml
  when: ansible_distribution in ('CentOS', 'RedHat') and zabbix_repo_enabled
  tags:
    - zabbix-repo 
