---
- name: "common | setting zabbix repo version"
  set_fact: 
    zabbix_repo_version: "{{ zabbix_repo_recommend[zabbix_repo_vars] }}"
  when: zabbix_repo_version is not defined
  tags:
    - zabbix-repo
 
#- debug: msg="Found configuration for {{ zabbix_repo_vars }}, release {{ zabbix_repo_version }}"
#  tags:
#    - zabbix-repo
 
- name: "common | set zabbix facts"
  set_fact:
    local_package: "{{ ansible_distribution }}/{{ zabbix_repo_releases[zabbix_repo_version] }}"
    remote_package: "/tmp/{{ zabbix_repo_releases[zabbix_repo_version] }}"
  tags:
    - zabbix-repo

- name: "common | copy package"
  copy: src={{ local_package }} dest={{ remote_package }}
  tags:
    - zabbix-repo
 
